// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import ScrollspyController from "./scrollspy_controller"
application.register("scrollspy", ScrollspyController)

import SparklineController from "./sparkline_controller"
application.register("sparkline", SparklineController)
